spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://localhost:9443/oauth2/jwks

  datasource:
    url: jdbc:postgresql://localhost:5432/ewalletdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: user-service
        format_sql: true
    show-sql: true
server:
  port: 8083